language: python
python:
  - "3.4"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "python create_local_settings.py"
# command to run tests
script:
  - "python website/manage.py createdb --nodata --noinput"
notifications:
  email: false
