language: python
python:
  - "3.4"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "python create_local_settings.py"
  - "pip install flake8"
# command to run tests
script:
  - "python website/manage.py createdb --nodata --noinput"
  - "python website/manage.py test website"
  - "flake8 website --statistics --exit-zero"
notifications:
  email: false
