sudo: false
language: python
python:
  - "3.4"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "python create_local_settings.py"
  - "pip install flake8"
  - "pip install coveralls"
# command to run tests
script:
  - "python -W ignore::DeprecationWarning website/manage.py createdb --nodata --noinput"
  - "python -W ignore::DeprecationWarning website/manage.py loaddata demo_data"
  - "coverage run website/manage.py test jdcore jdpages"
  - "flake8 website --statistics --exit-zero"
notifications:
  email: false
after_success:
  coveralls
