language: python
python:
  - "3.4"
# command to install dependencies
install:
  - "./build_env.sh"
  - "python create_local_settings.py"
# command to run tests
script:
  - "python website/manage.py migrate"
