site_name: 'jdwebsite'
docs_dir: 'docs'
repo_url: 'https://github.com/jonge-democraten/website'
site_author: 'Jonge Democration ICT-team'
copyright: Copyright &copy; Jonge Democration.
include_search: true
use_absolute_urls: true
theme: 'readthedocs'

pages:
- ['index.md', '', 'JD Website']
- ['user.md', '', 'User manual [NL]']
- ['developer.md', '', 'Developer manual']
- ['design.md', '', 'Design']
