site_name: 'jdwebsite'
docs_dir: './docs'
repo_url: 'https://github.com/jonge-democraten/website'
site_author: 'Jonge Democration ICT-team'
theme: 'readthedocs'

pages:
- ['index.md', 'Info', 'Documentation']
- ['user/index.md', 'User', 'Manual']
- ['developer/index.md', 'Developers', 'Installation']
- ['developer/quality.md', 'Developers', 'Quality']
- ['developer/logging.md', 'Developers', 'Logging']
- ['developer/testing.md', 'Developers', 'Testing']