site_name: 'jdwebsite'
docs_dir: './'
repo_url: 'https://github.com/jonge-democraten/website'
site_author: 'Jonge Democration ICT-team'
theme: 'readthedocs'

pages:
- ['index.md', 'Home']
- ['user/index.md', '', 'Users']
- ['developer/index.md', '', 'Developers']