site_name: jdwebsite docs
docs_dir: ./
repo_url: https://github.com/jonge-democraten/website
site_author: Jonge Democration ICT-team

pages:
- ['index.md', 'Introduction']
- ['user.md', 'Users']
- ['developer.md', 'Developers']
- ['testing.md', 'Testing']
