site_name: jdwebsite docs
docs_dir: ./docs
repo_url: https://github.com/jonge-democraten/website
site_author: Jonge Democration ICT-team

pages:
- ['index.md', 'Introduction']
- ['user.md', 'User manual']
- ['developer.md', 'Developer manual']
- ['testing.md', 'Testing']
